# Generated by Django 6.0.4 on 2026-05-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre_completo'], 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={'ordering': ['-anio'], 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_captura',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('observacion', 'Observación'), ('seguimiento', 'Seguimiento'), ('alerta', 'Alerta'), ('logro', 'Logro')], default='observacion', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='escolar.alumno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
