# Generated by Django 6.1.1 on 2026-10-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0002_alter_alumno_options_alter_semestre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoInicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('fallos', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'intento de inicio de sesión',
                'verbose_name_plural': 'intentos de inicio de sesión',
            },
        ),
    ]
